### ISSUE TITLE
input checkbox doesnt work with jquery 2.1.4

### ISSUE THREAD

**Issue by DotNet2Web** [dotCtor/jQuery.msgBox#16]
I use your msgbox in one of my solution, recently I upgraded my jquery version to <b>2.1.4.</b> After this upgrade the implementation of the checkbox doesnt work anymore. 

I traced the error to this piece of code.

$("input.msgButton").click(function (e) {
e.preventDefault();
var value = $(this).val();
if (options.type != "prompt") {
options.success(value);
}
else {
var inputValues = [];
$("div.msgInput input").each(function (index, domEle) {
var name = $(this).attr("name");
var value = $(this).val();
var type = $(this).attr("type");

if (type === "checkbox" || type === "radiobutton") {
                    <b>inputValues.push({ name: name, value: value, checked: $(this).attr("checked") });</b>
}
else {
inputValues.push({ name: name, value: value });
}
});
options.success(value, inputValues);
}
hide();
});

<b>Fix:</b> 
If you change the push row for a checkbox or radiobutton into:
<b>inputValues.push({ name: name, value: value, checked: $(this).prop("checked") });</b>

Then it works again!

**Comment by koppor** [comment]
Please create a pull request.
